### ISSUE TITLE
har file

### ISSUE THREAD

**Issue by Zeeetu** [maxtheaxe/youtube-handles#2]
what sort of .har file should I provide? I'm getting an error

**Comment by maxtheaxe** [comment]
hahaha I hadn't even finished writing the code yet, give me a few hours and I'll write up instructions as well

**Comment by maxtheaxe** [comment]
@Zeeetu see the updated program and instructions, let me know if you still need help

if you want to wait, I'll make a video later

**Comment by zeeetu** [comment]
nice, clear instructions provided. one thing I have an issue with is everytime I try to run the program through cmd normally, it tells me that im missing the haralyzer package even though I have it installed. I fixed this by adding "sys.path.append(path to python packages folder)" to the code. now the program works, but for some reason only checks one username from the list and then raises an error and tells me that youtube logged me out.

**Comment by maxtheaxe** [comment]
it should be fixed now—see if updating to the most recent version helps

**Comment by zeeetu** [comment]
still getting similiar error, checks one username then raises an exception.

**Comment by maxtheaxe** [comment]
I just made a [video walkthrough](https://youtu.be/7Zqjw5O6wd8). Double check the instructions there, please, and if you're still having issues, then send me the exception and whatever other information you think would help me narrow down the problem.

**Comment by zeeetu** [comment]
thank you for the video instructions, the issue I was having was because I was using a fairly new account and I used chrome to save the HAR file. it's working perfectly now.

**Comment by maxtheaxe** [comment]
Awesome, enjoy! Let me know if you run into any other issues.
